default: &default
  adapter: postgresql
  encodiong: utf8
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["APPLICATION_SLUG"] %>_development

test:
  <<: *default
  database: <%= ENV["APPLICATION_SLUG"] %>_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: <%= ENV["APPLICATION_SLUG"] %>_production
