source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.4'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'devise', '~> 4.7.1'
gem 'faraday', '~> 0.15.4'
gem 'friendly_id', '~> 5.2.4'
gem 'jbuilder', '~> 2.7'
gem 'kaminari', '~> 1.1.1'
gem 'omniauth-google-oauth2', '~> 0.8.0'
gem 'pg', '~> 1.1.4'
gem 'puma', '~> 3.11'
gem 'rails', '~> 6.0.0'
gem 'rails_admin', '~> 2.0'
gem 'ransack', '~> 2.3.0'
gem 'react-rails', '~> 2.6.0'
gem 'sass-rails', '~> 5'
gem 'stringex', '~> 2.8.5'
gem 'textacular', '~> 5.2.0'
gem 'turbolinks', '~> 5'
gem 'webpacker', '~> 4.0'

group :development, :test do
  gem 'bundler-audit'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'rubocop'
  gem 'rubocop-checkstyle_formatter'
  gem 'shoulda-matchers'
  gem 'webmock', require: false
end

group :development do
  gem 'bullet', '~> 6.0.2'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
